"""Added password string to 512.

Revision ID: 095d13dc155b
Revises: 0e6861661f09
Create Date: 2025-02-02 21:17:27.691127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095d13dc155b'
down_revision = '0e6861661f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
