"""Added something.

Revision ID: 0e6861661f09
Revises: 25f329d4d029
Create Date: 2025-01-29 16:35:31.457968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6861661f09'
down_revision = '25f329d4d029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.alter_column('class_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.alter_column('class_time',
               existing_type=sa.String(length=128),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
